/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo_final;


import PruebaSonido.Sonido;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
/**
 *
 * @author Orlando
 */
public class Menu extends javax.swing.JFrame {
    private FileOutputStream fos;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;
    private FileInputStream fis;
    private Main Juego;
    private Main PartidaLeida;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
//        this.setUndecorated(true);
        this.setLocationRelativeTo(null);
    }

    public void setJuego(Main Juego) {
        this.Juego = Juego;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Regresar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        stopmusic = new javax.swing.JButton();
        playmusic = new javax.swing.JButton();
        ReadGame = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(820, 820));

        Regresar.setText("Regresar");
        Regresar.setAlignmentX(410.0F);
        Regresar.setAlignmentY(410.0F);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar Partida");
        Guardar.setAlignmentX(410.0F);
        Guardar.setAlignmentY(410.0F);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.setAlignmentX(410.0F);
        Salir.setAlignmentY(410.0F);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        stopmusic.setText("Detener musica");
        stopmusic.setAlignmentX(410.0F);
        stopmusic.setAlignmentY(410.0F);
        stopmusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopmusicActionPerformed(evt);
            }
        });

        playmusic.setText("Escuchar musica");
        playmusic.setAlignmentX(410.0F);
        playmusic.setAlignmentY(410.0F);
        playmusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playmusicActionPerformed(evt);
            }
        });

        ReadGame.setText("Leer Partida");
        ReadGame.setAlignmentX(410.0F);
        ReadGame.setAlignmentY(410.0F);
        ReadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(playmusic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stopmusic))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Regresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopmusic, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playmusic, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        boolean aux=true;
        this.Juego.ActualizarPepitoX();
        this.Juego.ActualizarPepitoY();
        try {
            
             fos = new FileOutputStream("Save.wop");
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        }
        System.out.println(Juego.toString());
        try{
        oos=new ObjectOutputStream(fos);
        }catch(FileNotFoundException e){
            e.printStackTrace();
        }catch(IOException e){
            e.printStackTrace();
        }
        
        ObjectInputStream ois = null;
        
        try {
            ois = new ObjectInputStream(new FileInputStream("Save.wop"));
        } catch (FileNotFoundException ex) {
            aux=false;
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        if(aux){              
            try{
                System.out.println(Juego);
                oos.writeObject(this.Juego);
                
                System.out.println("Guardado exitoso");
            }catch(IOException e){
                e.printStackTrace();
            }finally{
                try{
                    ois.close();
                    oos.close();
                    
                    //oos.close();
                }catch(IOException e){
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void stopmusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopmusicActionPerformed
        Sonido.BACK.stop();
    }//GEN-LAST:event_stopmusicActionPerformed

    private void playmusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playmusicActionPerformed
        Sonido.BACK.loop();
    }//GEN-LAST:event_playmusicActionPerformed

    private void ReadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadGameActionPerformed
        this.Juego.thread.stop();
        this.LeerPartida();
        this.Juego.thread.start();
        
    }//GEN-LAST:event_ReadGameActionPerformed

    private Main LeerPartida(){   
        try {
            fis = new FileInputStream("Save.wop");
            System.out.println(Juego.toString()+" "+1);
        } catch (FileNotFoundException ex) {
            System.out.println(Juego.toString()+" Fallo: "+1);
            ex.printStackTrace();
        }
        try {
            ois = new ObjectInputStream(fis);
             System.out.println(Juego.toString()+" "+2);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
            System.out.println(Juego.toString()+" Fallo: "+2.1);
        } catch (IOException ex) {
            ex.printStackTrace();
            System.out.println(Juego.toString()+" Fallo: "+2.2);
        }
        
        try {
           System.out.println(Juego.toString());
           Juego = (Main) ois.readObject();
           System.out.println(Juego.toString());
        } catch (IOException ex) {
           ex.printStackTrace();
           System.out.println(Juego.toString()+" Fallo: "+3);
        } catch (ClassNotFoundException ex) {
           ex.printStackTrace();
           System.out.println(Juego.toString()+" Fallo: "+3.1);
        } finally{
            if (ois != null){
                try {
                    ois.close();
                    fis.close();
                } catch (IOException ex) {
                    ex.printStackTrace();
                    System.out.println(Juego.toString()+" Fallo: "+4);
                }
            
            }
            return PartidaLeida;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton ReadGame;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playmusic;
    private javax.swing.JButton stopmusic;
    // End of variables declaration//GEN-END:variables
}
